<?php
namespace controllers;
use components\slim\Slim;
use models\TopList;

/**
 * Created by PhpStorm.
 * User: nnikitchenko
 * Date: 18.11.2015
 *
 */
class March8Controller extends GetGiveRateController
{
    protected $action_type = 'march82018';
    protected $image = 'https://i.oldbk.com/i/i/quest_0803_top%d_%s.png';

    public function __construct(Slim $container, $action, $year = 2016)
    {
        $this->year = (int)$year;

        $this->action_type = 'march8'.$this->year;
        if($year == 2016) {
            $this->action_type = 'march8';
        }

        parent::__construct($container, $action);
    }

    public function beforeAction($action)
    {
        if(in_array($action, array('search'))) {
            $this->cache = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function prepareImg($user, $position)
    {
        return sprintf($this->image, $position, $user['sex'] == 1 ? 'm' : 'w');
    }

    protected function getKeyCache()
    {
        return sprintf('html_%s_%s_%s', $this->getControllerId(), $this->actionId, $this->year);
    }
}